image: maven:3-openjdk-18-slim

stages:
  - build
  - deploy

build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - mvn clean install -Dspring.profiles.active=prod
  artifacts:
    paths:
      - /home/gitlab-runner/*.jar

deploy:
  stage: deploy
  only:
    - master
  script:
    - kill $(cat ./pid.file)
    - java -jar -Djda.token=$TOKEN -Dspring.profiles.active=prod kataplusbot-0.0.1-SNAPSHOT.jar & echo $! > ./pid.file &